name: Docker Build & Push

on:
  push:
    branches:
      - "docker-build"

permissions:
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  login:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Build the stack      
        run: docker-compose build --file ./docker-compose.yml
        
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pastebin:1.0