name: Docker Build & Push

on:
  push:
    branches:
      - "docker-build"

permissions:
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  docker-build-push:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with: 
          images: npvietkhoa/pastebin

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          file: docker-compose.yml
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}